# Generated by Django 4.2.1 on 2023-05-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ZIP", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Sites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.TextField(max_length=255)),
                ("Site_Name", models.TextField(max_length=255)),
                ("Address_1", models.TextField(max_length=255)),
                ("City", models.TextField(max_length=255)),
                ("County", models.TextField(max_length=255)),
                ("ZIP", models.TextField(max_length=255)),
                ("site_type", models.TextField(max_length=255)),
                ("Latitude", models.FloatField()),
                ("Longitude", models.FloatField()),
            ],
        ),
    ]
