# Generated by Django 4.2.1 on 2023-05-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0004_remove_sites_id_alter_sites_zip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites",
            name="Longitude",
            field=models.FloatField(max_length=20),
        ),
    ]
