# Generated by Django 4.2.1 on 2023-05-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0006_alter_sites_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[("id", models.IntegerField(primary_key=True, serialize=False)),],
        ),
    ]
