# Generated by Django 4.2.1 on 2023-05-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0007_test"),
    ]

    operations = [
        migrations.DeleteModel(name="Test",),
        migrations.AlterField(
            model_name="sites",
            name="Longitude",
            field=models.FloatField(max_length=20),
        ),
    ]
