# Generated by Django 4.2.1 on 2023-05-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0008_delete_test_alter_sites_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites", name="ZIP", field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="sites",
            name="uuid",
            field=models.TextField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
