# Generated by Django 4.2.1 on 2023-05-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0009_alter_sites_zip_alter_sites_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites",
            name="Latitude",
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sites", name="uuid", field=models.TextField(max_length=255),
        ),
    ]
