# Generated by Django 4.2.1 on 2023-05-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Website", "0013_alter_sites_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sites",
            name="Longitude",
            field=models.FloatField(max_length=20),
        ),
    ]
